### ISSUE TITLE
Usability: Emails are case-sensitive

### ISSUE THREAD

**Issue by ChrisAntaki** [spacedogXYZ/call-power#1]
Just took me a minute to log in, because I always capitalize two letters in my email, but the system was looking for an exact match of a totally lowercase email.

If the username & email in the login were case insensitive, that would be more usable, at least for people like me that throw capitals in there.

**Comment by jlev** [comment]
Thanks Chris, just resolved this with df3293d.

We'll be tagging 1.0.0 soon. Any other feedback before then?

**Comment by ChrisAntaki** [comment]
Thanks! Will keep you posted
