### ISSUE TITLE
Segment by location in custom target lists

### ISSUE THREAD

**Issue by jlev** [spacedogXYZ/call-power#29]
For campaigns which target congressional committees or leadership, it would be helpful to have a way to still segment callers by location. They should be routed to their own rep or senator first, then the rest of the list.

This is much more difficult with fully custom targets, but for congress we should be able to route people locally first.

**Comment by harpojaeger** [comment]
(and ideally the "route callers to the rest of the list after their own members" feature should be user-configurable.)

**Comment by jlev** [comment]
This is now doable in v1.3 by setting Include Special Targets to "Only If" Users' Representatives.

We can consider adding an ordering priority, but the targeting UI is already fairly complex. May be worth a full redesign before adding new toggles.

**Comment by jlev** [comment]
merged to 1.3 and released
