### ISSUE TITLE
Uploaded WAV files sound like static when played during a twilio call

### ISSUE THREAD

**Issue by copperwall** [spacedogXYZ/call-power#31]
If you upload a WAV file for one of the audio fields, it sounds like static during the twilio phone call. Previewing the file in the admin interface works correctly though.

Downloading the file from the S3 bucket it was uploaded to shows a `Content-Type` of `audio/mpeg`, but the file has the file signature of a WAV file instead of an MP3. Maybe the browser is a little more accepting of file type mismatches than the Twilio API.

**Comment by jlev** [comment]
Interesting. The admin interface records mp3 using https://github.com/zhuker/lamejs and https://github.com/sb2702/audioRecord.js.git, and I'll admit I haven't tested with other file types. Twilio should also accept wav, uLaw or aiff.

The upload to s3 does assume a .mp3 extension when uploading to S3 (https://github.com/spacedogXYZ/call-power/blob/master/call_server/campaign/views.py#L192), which may be incorrect. That's probably what's causing Twilio to barf on playing back.

I'll fix that assumption and set the file extension based on the originally uploaded file.
