### ISSUE TITLE
Warn user if uploaded voice file is in an unsupported format

### ISSUE THREAD

**Issue by wioux** [spacedogXYZ/call-power#37]
If you upload a file in e.g. mp4a format and it ends up on S3 as .mp3, Twilio can't play it and reports the error in a really confusing way on their console.

The supported formats are:

https://www.twilio.com/docs/api/twiml/play

**Comment by jlev** [comment]
Thanks @wioux, this is also related to #31. I'll try to fix both together in v1.1.4

**Comment by wioux** [comment]
Thanks @jlev!
