### ISSUE TITLE
unicode error re: NJ senator Menéndez

### ISSUE THREAD

**Issue by mfb** [spacedogXYZ/call-power#38]
we hit UnicodeEncodeError call_server.political_data.adapters in adapt
'ascii' codec can't encode character u'\xe9' in position 3: ordinal not in range(128)

Is this issue affecting other folks or unique to our instance?

**Comment by jlev** [comment]
Not unique to you. The String.format function in Python 2.7 requires an explicitly unicode string. Fixed in b936cc6e2fc4ca485a7a781419c2a253c662bd48
