### ISSUE TITLE
gracefully handle vacant congressional districts

### ISSUE THREAD

**Issue by mfb** [spacedogXYZ/call-power#39]
We hit an exception for users in vacant congressional district (e.g. CA district 34*)

TypeError: 'NoneType' object has no attribute '__getitem__'

In our case the call could have continued because they still had 2 senators they could call.

A related issue is occasional "undefined" congressional districts - although I didn't yet figure out why this is happening; maybe failure to geolocate their address.

\* https://en.wikipedia.org/wiki/California's_34th_congressional_district

**Comment by jlev** [comment]
Yikes, we may need some try/except blocks in the make_single function. Do you have a traceback of where the exception was triggered? The political_data adapters should be resilient to that sort of error.

**Comment by mfb** [comment]
looks like the bug is triggered at `rep = self.get_house_member(state, district)[0]`

**Comment by jlev** [comment]
Thanks for the report, I've hotfixed in 1.1.5 to resolve this issue.

There's been a lot of changes to the political_data parsing in v1.2 to make it international. This includes getting the valid targets from generators, which won't exhibit the same problem.
