### ISSUE TITLE
STORE_S3_REGION comparison is wrong

### ISSUE THREAD

**Issue by owlishness** [spacedogXYZ/call-power#60]
call_server/config.py
         # http://docs.aws.amazon.com/general/latest/gr/rande.html#s3_region
         # use path-style urls, in case bucket name is DNS incompatible (uses periods, or mixed case
         # http://docs.aws.amazon.com/AmazonS3/latest/dev/BucketRestrictions.html
-        if STORE_S3_REGION is 'us-east-1':
+        if STORE_S3_REGION == 'us-east-1':

**Comment by jlev** [comment]
merged to 1.3 and released
